---
title: "reading_data_from_the_web.Rmd"
output: github_document
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)
library(httr)
```


```{r, message=FALSE, warning=FALSE}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html

drug_use_html %>%
  html_table()


table_marj = 
  drug_use_html %>% 
  html_table() %>% 
  first() %>%
  slice(-1) 

table_marj
```

### learning assesement:
```{r, message=FALSE, warning=FALSE}
ny_living = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>% 
  html_table(header = TRUE) %>% 
  first()
```


```{r, message=FALSE, warning=FALSE}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")

title_vec = 
  swm_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

gross_rev_vec = 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_elements(".runtime") %>%
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```



```{r, message=FALSE, warning=FALSE}

```



```{r, message=FALSE, warning=FALSE}

```



```{r, message=FALSE, warning=FALSE}

```
